# Generated by Django 6.0.7 on 2026-09-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BedAndBreakfast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='include',
            name='codiceprenotazione',
            field=models.ForeignKey(db_column='codicePrenotazione', on_delete=django.db.models.deletion.CASCADE, to='BedAndBreakfast.prenotazione'),
        ),
        migrations.AlterField(
            model_name='include',
            name='nomeservizio',
            field=models.ForeignKey(db_column='nomeServizio', on_delete=django.db.models.deletion.PROTECT, to='BedAndBreakfast.servizioaggiuntivo'),
        ),
        migrations.AlterField(
            model_name='occupante',
            name='codiceprenotazione',
            field=models.ForeignKey(db_column='codicePrenotazione', on_delete=django.db.models.deletion.CASCADE, to='BedAndBreakfast.prenotazione'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='codicepagamento',
            field=models.AutoField(db_column='codicePagamento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='codiceprenotazione',
            field=models.OneToOneField(db_column='codicePrenotazione', on_delete=django.db.models.deletion.CASCADE, to='BedAndBreakfast.prenotazione'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='codiceprenotazione',
            field=models.AutoField(db_column='codicePrenotazione', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='datainiziostagione',
            field=models.ForeignKey(blank=True, db_column='dataInizioStagione', null=True, on_delete=django.db.models.deletion.PROTECT, to='BedAndBreakfast.stagione'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='documentoidentitaospite',
            field=models.ForeignKey(db_column='documentoIdentitaOspite', on_delete=django.db.models.deletion.PROTECT, to='BedAndBreakfast.ospite'),
        ),
        migrations.AlterField(
            model_name='pulizia',
            name='documentoidentitaaddetto',
            field=models.ForeignKey(db_column='documentoIdentitaAddetto', on_delete=django.db.models.deletion.PROTECT, to='BedAndBreakfast.personale'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='codiceprenotazione',
            field=models.OneToOneField(db_column='codicePrenotazione', on_delete=django.db.models.deletion.CASCADE, to='BedAndBreakfast.prenotazione'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='codicerecensione',
            field=models.AutoField(db_column='codiceRecensione', primary_key=True, serialize=False),
        ),
    ]
